### PR TITLE
Add virtual package support to apt provider

### PR DESCRIPTION
**Pull request by sometimesfood**
This pull request adds virtual package support to the apt provider. This is work in progress.

@andis Could you have a look at this and let me know whether it is sufficiently readable for a person familiar with Debian who is not me? The interesting changes are those in `provider/package/apt.rb` (see below).

The basic idea behind this is:
- If no regular (=non-virtual) version of a package is installed, call `apt-cache showpkg package_name`.
- In the output, locate the `Reverse-Provides` line and iterate over the list of packages providing the virtual package.
- If any of the packages that provides the virtual package is installed, the virtual package is installed.

### CODE REVIEW

**Comment by andis** [comment]
Please split out command output parsing lib/wright/provider/package/apt.rb into separate methods, the intent is not obvious.

**Comment by sometimesfood** [comment]
Fair enough. The new version (2251fa8) should be much easier on the eyes. Better?

**Comment by andis** [comment]
Yes, I can follow the code much better now.

**Comment by sometimesfood** [comment]
Glad to hear that. Thanks for the review. Merging.

**Pull request merged**
